#! /bin/bash
# runmakefile
# Geoffrey Hannigan
# Pat Schloss Lab
# University of Michigan
# Use this to submit the makefile to the server

#PBS -N runmakefile-conjviribus
#PBS -q fluxod
#PBS -l qos=flux
#PBS -l nodes=1:ppn=4,mem=32GB
#PBS -l walltime=50:00:00
#PBS -j oe
#PBS -V
#PBS -A pschloss_fluxod

# Set the proper R module
module load R/3.3.3
module load virsorter
module load perl-modules
module load bioperl/1.6.1
module load bowtie2

# Set working directory
cd /nfs/turbo/schloss-lab/ghannig/Hannigan-2016-ConjunctisViribus || exit

# Run contig validation loop
mkdir -p ./data/SecondaryBenchmarkingSet_1
bash ./bin/BenchmarkingModel_SecondaryValidation.sh ./data/genbankPhageHost/VirRef/virus.fragment.1.fa ./data/genbankPhageHost/BacRef/bacteria.fragment.1.fa ./data/SecondaryBenchmarkingSet_1/BenchmarkCrisprsFormat_1.tsv ./data/SecondaryBenchmarkingSet_1/BenchmarkProphagesFormatFlip_1.tsv ./data/SecondaryBenchmarkingSet_1/MatchesByBlastxFormatOrder_1.tsv ./data/SecondaryBenchmarkingSet_1/PfamInteractionsFormatScoredFlip_1.tsv "SecondaryBenchmarkingSet_1"
