#! /bin/bash
# runmakefile
# Geoffrey Hannigan
# Pat Schloss Lab
# University of Michigan
# Use this to submit the makefile to the server

#PBS -N DownloadPublishedVirome
#PBS -A pschloss_flux
#PBS -q flux
#PBS -l qos=flux
#PBS -l nodes=1:ppn=12,mem=64GB
#PBS -l walltime=100:00:00
#PBS -j oe
#PBS -V

make
