#! /bin/bash

echo Rendering now...

pandoc --template=customtemplate.tex -H options.sty -s ./manuscript.md -f markdown -t latex -o ./manuscript.pdf --biblio=citations.bib --csl=./nature.csl

echo Done
