#! /bin/bash

echo Rendering now...

pandoc -H options.sty -S --toc ./manuscript.md -f markdown -t latex -o ./manuscript.pdf --biblio=citations.bib --csl=/Users/Hannigan/git/styles/nature.csl

echo Done
